### ISSUE TITLE
06 - Banco de dados e upload de arquivos no Node : Error na descrição

### ISSUE THREAD

**Issue by Laerciosantosn** [Rocketseat/bootcamp-gostack-desafios#26]
Nas especificações  dos teste pede para criar um banco de dados com o nome "gostack_desafio06_tests" para que todos os testes possam executar corretamente.
No entanto no arquivo ormconfig.json o "database" esta configurado para acessar o banco de dados "gostack_desafio06".
Faltou adicionar a informação para o usuário alterar a porta caso este utilize uma porta diferente da 5432 para que ele possa executar os testes e antes de enviar o repositório para o github voltar a configuração da porta correta.

**Comment by josepholiveira** [comment]
Fala @Laerciosantosn !

No ormconfig, ele realmente utiliza o `gostack_desafio06`, os testes utilizam uma database diferente para que os testes rodem em um banco separado, e essa lógica está dentro do arquivo de configuração do banco de dados.

Quanto a configuração das portas, acredito que esse seja um processo padrão do usuário conferir as configurações de banco de dados e variáveis ambiente, por exemplo. Mas vamos verificar no que podemos melhorar nesse processo!
