### ISSUE TITLE
Desafio 07: GoFinances Web - Erro na descrição

### ISSUE THREAD

**Issue by vitortolentino** [Rocketseat/bootcamp-gostack-desafios#29]
Na descrição da instalação dos `types` de `cors`, fala informar a flag `-D`, para instalação apenas em ambiente de desenvolvimento.
Tendo isso em vista, sabemos que a lib `cors` será instalada juntamento com a lib de tipos. Então para que o `cors` seja instalado como uma `dependencia` e não uma `dependência de desenvolvimento`, precisamos instalar o `cors` antes de instalar os tipos.  

Cenário atual:

> Antes de tudo, para que seu frontend se conecte corretamente ao backend, vá até a pasta do seu backend e execute o comando `yarn add cors @types/cors`.

Esperado:

> Antes de tudo, para que seu frontend se conecte corretamente ao backend, vá até a pasta do seu backend e execute os comandos `yarn add cors` e depois `yarn add cors @types/cors -D`.

**Comment by josepholiveira** [comment]
Faala @vitortolentino !

Obrigado pelo report, já atualizei isso lá! 🚀
