### ISSUE TITLE
Desafio 02: NodeJS - Erro na descrição ou no teste "should be able to give a like to the repository"

### ISSUE THREAD

**Issue by TiagoCunhaF** [Rocketseat/bootcamp-gostack-desafios#44]
Existe um erro entre as instruções e o teste.

Notem que nas instruções esta:

> should be able to give a like to the repository: Para que esse teste passe, sua aplicação deve permitir que um repositório com o id informado possa receber likes. O valor de likes deve ser incrementado em 1 a cada requisição, e **como resultado, retornar um json contendo o repositório com o número de likes atualizado**.

O problema no meu entendimento é que o teste apenas espera o objeto {likes: 1}. Porem como podem conferir acima, esta solicitando que seja retornado o json contendo o repositório ou seja:
```
{
  id: '6d10d2bf-9905-44e3-8f51-0eaf5cc55935',
  title: 'Umbriel',
  url: 'https://github.com/Rocketseat/umbriel',
  techs: [ 'Node', 'Express', 'TypeScript' ],
  likes: 1
}
```

Porem o teste falha pois o mesmo espera: 
`
    expect(response.body).toMatchObject({
      likes: 1,
    });
`

**Comment by josepholiveira** [comment]
Faala @TiagoCunhaF, beleza?

O que a função toMatchObject faz e verificar se no objeto que foi recebido existe algumas propriedades, nesse caso o likes, e o teste deveria funcionar normalmente mesmo recebendo outras propriedades.

No mais, se o erro persistir recomendo que poste os logs/codigos no Forum dos alunos para que os instrutores possam te ajudar melhor.

Abraços!
