### ISSUE TITLE
Desafio 07: GoFinances Web - Erro na descrição

### ISSUE THREAD

**Issue by stevescruz** [Rocketseat/bootcamp-gostack-desafios#47]
Na descrição do README.md está pedindo para criar uma tabela com o campo `category`.

> - Listar as transações da sua API: Sua página Dashboard deve ser capaz de exibir uma listagem através de uma tabela, com o campo `title`, `value`, `type` e `category` de todas as transações que estão cadastradas na sua API.

Porém o correto seria substituir a palavra `category` por `date`, já que no layout da aplicação GoFinances Web no Figma é o campo data que é utilizado.

**Comment by josepholiveira** [comment]
Faala @stevescruz !

Se você der uma olhada, no figma ele mostra também o campo category, então acaba não faz sentido remover esse dessa listagem haha 

Na descrição do README nós colocamos apenas campos que são validados pelo teste, e a parte de datas nós não validamos por conta que há várias formas de lidar com datas, e como esse não era o objetivo do desafio, ficou por fora dessa validação!

Abraços!

**Comment by stevescruz** [comment]
@josepholiveira Escrevi incorretamente, na verdade quis dizer que é o campo 'type' que não tem no layout do Figma. O campo 'category' realmente tem.
